### ISSUE TITLE
No devices or entities detected 

### ISSUE THREAD

**Issue by santypav** [gillesvs/librelink#10]
Hello, and thank you for your great work. 

I have installed version 1.2.0 and it does not recognize any **devices or entities**. 

I am using my librelink account (not librelinkup, which does not recognize it) and the global node since I am in Spain. 

Do i have to do something else?

![image](https://github.com/gillesvs/librelink/assets/81905302/6cf10308-e401-498f-af2c-ff953e4c9738)

**Comment by gillesvs** [comment]
Hello,
Can you activate the debug mode and send me the file please (deleting password if you share it here)

**Comment by santypav** [comment]
[librelinkLog.log](https://github.com/gillesvs/librelink/files/14278663/librelinkLog.log)
I only find this, is this what you ask?

**Comment by gillesvs** [comment]
> [librelinkLog.log](https://github.com/gillesvs/librelink/files/14278663/librelinkLog.log) I only find this, is this what you ask?

Hello,
Yes this is the file I am looking for. And your account retreive 0 patients.
You need to use librelink account and not librelinkup (followers). Is it the case?
Do you already use librelinkup? Because you need to accept Abbott legal terms for the API to work.

**Comment by santypav** [comment]
Yes, I use my librelink account, sure. The same that I see in my app with my sensor freestyle libre 2.
I have a librelinkup account but take an error to login. 

Where can I accept Abbott legal terms for the api?? Can you put here a link?

**Comment by santypav** [comment]
Brilliant! After changing the password to the Librelinkup user, I was able to start the integration with that profile and it successfully imported the patient data. Thank you very much for everything.
