### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by fastrack20** [gillesvs/librelink#14]
** Which country are you from **
Canada

**Describe the bug**
Can't seem to get the integration to run. I checked my credentials with the LibreLink app and they are correct. I am getting the message "Unknown error occurred" when trying to set up the integration.

**Log file**

[librelinkLog.log](https://github.com/gillesvs/librelink/files/14462852/librelinkLog.log)

**Additional context**
I did try after to purposely enter the wrong password and I did get an invalid username or password error. I did validate that my credentials seem to be working. I tried using https://libreview-unofficial.stoplight.io/ and I get a 200 response when running the login. It also provides my information such as name, email, country and a what appears to be a valid token.

**Comment by gillesvs** [comment]
Hello @fastrack20 ,
Did you use LibreLinkUp app credentials and not librelink? It only works with LibreLinkUp credentials.

**Comment by toblob89** [comment]
I have the same issue and I cannot log in with my credential. It was working until this morning.

**Comment by toblob89** [comment]
Yes in librelinkup app working perfectly fine and indeed it was working with the Integration until this morning, then stopped working. Is there an update on librelinkup server which causes this issue?

**Comment by gillesvs** [comment]
> Yes in librelinkup app working perfectly fine and indeed it was working with the Integration until this morning, then stopped working. Is there an update on librelinkup server which causes this issue?

Hello @fastrack20 @toblob89 
You seem to be both on the American zone... maybe the did update an url for the API. On my side I have no problem (europe) so I cannot debug....
do you know your API url? because today the integration is using the global one except for Russia. Maybe this is the issue.

Abbott do not provide any documentation.

**Comment by toblob89** [comment]
Hello Gilles, I am in the european User.Surprisingly yesterday I was able to log in via librelinkup app whereas it was not possible to do so via HA Integration. Again suprising this morning it was working and is still working fine again. Maybe some issue on abbot server side ?

**Comment by gillesvs** [comment]
> I manually changed the URL in const.py to api-ca.libreview.io and it worked with the integration.

Hello,

I was going to suggest this :-)

So I will add Canada as a choice for the next release mapped with api-ca URL

Thanks for the feedback

**Comment by dashernln** [comment]
I'm sorry, but it seems that api-de also exists, i will check it out

**Comment by gillesvs** [comment]
Yes indeed, as ...-fr. But as it works with the global endpoint i didn't
botter to use it

**Comment by dashernln** [comment]
yes, it would be better to use one global point, but abbot "think differently". i`ve forked repo, added de api server, now it works. 
many thanks, it is very useful integration.

**Comment by gillesvs** [comment]
> yes, it would be better to use one global point, but abbot "think differently". i`ve forked repo, added de api server, now it works. many thanks, it is very useful integration.

Hello @dashernln ,
You are in Germany and the global API does not work?

If so I will add all local endpoint in the configuration. They are already listed in the const.py but  I did not thought they were usefull.
