### ISSUE TITLE
Getting values from 2 patients

### ISSUE THREAD

**Issue by MarkusKetola** [gillesvs/librelink#2]
If you follow two patients in Libreview, the values received are combined to same sensor. Can this be separated?

**Comment by inakiarredondo** [comment]
Agree. When you are monitoring several users under your account, it would be great if we could select the one we are going to integrate. Even better, if we could add the integration several times, for the different users. 
PS: than you @gillesvs for creating this integration. it is really useful.

**Comment by gillesvs** [comment]
Hello,

I can try based on the API documentation, but I use a single account and therfore I do not have data to validate multiple accounts.
I will add this in the request list for the next release.

**Comment by gillesvs** [comment]
> If you follow two patients in Libreview, the values received are combined to same sensor. Can this be separated?

Can you send me a screen shot to be sure i understand the result?

**Comment by KetolaSami** [comment]
![image](https://github.com/gillesvs/librelink/assets/124524749/cc2b5804-3118-45a5-ad4a-4a76a81904ab)
The same period zoomed in

**Comment by MarkusKetola** [comment]
If you need, I can add you to recipient to my sons libre3 data. It needs just your e-mail address, if I remember correctly?

**Comment by gillesvs** [comment]
> If you need, I can add you to recipient to my sons libre3 data. It needs just your e-mail address, if I remember correctly?

Yes thanks, that would greatly help to implement the feature: gilles.vanschendel@gmail.com

**Comment by MarkusKetola** [comment]
Sorry, I tried that, but we shoud be using the same localization settings. So, it did not allow to add you...

**Comment by inakiarredondo** [comment]
Same here. I also tried to add you @gillesvs but got the same message.
You could probably create a new librelink/libreview account with Spain (in my case) as region, but then you will not be able to invite yourself, so we are back to square one...

**Comment by gillesvs** [comment]
> Same here. I also tried to add you @gillesvs but got the same message. You could probably create a new librelink/libreview account with Spain (in my case) as region, but then you will not be able to invite yourself, so we are back to square one...

I think I can guess the output for multiple patients. I will propose a test version in the days to come.

**Comment by gillesvs** [comment]
Version 1.1.3 has been released to manage multiple patients per account.
I did try to guess the API result.
I also catch the API response in the DEBUG. So please send me the logs (enable logging) if it does not work

read the warning in the release note ;-)

**Comment by mkotek** [comment]
I have Managed to get it running.
The problem is, value is not updated, even though in debug, I can see new readouts with changed values. But time since last measurement now reads 35 minutes.

**Comment by gillesvs** [comment]
> I have managed to get it running.
> The problem is, value is not updated, even though in debug, I can see new readouts with changed values. But time since last measurement now reads 35 minutes.

Yes i fixed it in 1.1.5
Just download last beta version in hacs directly

**Comment by alexanderznamensky** [comment]
Dear @gillesvs!
Thanks for great work! It is really useful for diabet control!
In my case I cannot add second patient.
Once the second patient appeared, but the first one disappeared. Now when adding I get an error:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
First occurred: 10:37:45 (56 occurrences)
Last logged: 12:05:49

Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-c1a9c786a4021b4afdddd9de55bcbe2b-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2
Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-value already exists - ignoring sensor.veronika_znamenskaia_glucose_measurement_2
Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-trend already exists - ignoring sensor.veronika_znamenskaia_glucose_trend_2
Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-sensor already exists - ignoring sensor.veronika_znamenskaia_active_sensor_2
Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2

**Comment by gillesvs** [comment]
> Dear @gillesvs! Thanks for great work! It is really useful for diabet control! In my case I cannot add second patient. Once the second patient appeared, but the first one disappeared. Now when adding I get an error:
> 
> Logger: homeassistant.components.sensor Source: helpers/entity_platform.py:610 First occurred: 10:37:45 (56 occurrences) Last logged: 12:05:49
> 
> Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-c1a9c786a4021b4afdddd9de55bcbe2b-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-value already exists - ignoring sensor.veronika_znamenskaia_glucose_measurement_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-trend already exists - ignoring sensor.veronika_znamenskaia_glucose_trend_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-sensor already exists - ignoring sensor.veronika_znamenskaia_active_sensor_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2

Thanks for feedback.
Can you pass the integration in debug mode and send me the log?
So I will finally have a look at the API response for multiple patients (as for now, I am simply guessing as Abbott does not provide official documentation of their API)
Indeed, as Veronika should be a patient and not the account owner, it should not create duplicate Ids.... but there is something I do not see, that is why i need logs.
Thanks to be part of this "blind" debugging session ;-)
gilles

**Comment by alexanderznamensky** [comment]
> > Dear @gillesvs! Thanks for great work! It is really useful for diabet control! In my case I cannot add second patient. Once the second patient appeared, but the first one disappeared. Now when adding I get an error:
> > Logger: homeassistant.components.sensor Source: helpers/entity_platform.py:610 First occurred: 10:37:45 (56 occurrences) Last logged: 12:05:49
> > Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-c1a9c786a4021b4afdddd9de55bcbe2b-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-value already exists - ignoring sensor.veronika_znamenskaia_glucose_measurement_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-trend already exists - ignoring sensor.veronika_znamenskaia_glucose_trend_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-sensor already exists - ignoring sensor.veronika_znamenskaia_active_sensor_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2
> 
> Thanks for feedback. Can you pass the integration in debug mode and send me the log? So I will finally have a look at the API response for multiple patients (as for now, I am simply guessing as Abbott does not provide official documentation of their API) Indeed, as Veronika should be a patient and not the account owner, it should not create duplicate Ids.... but there is something I do not see, that is why i need logs.
> 
> The **expected behavior** is, for a single account, to have as many devices created as there are patients, with sensors prefixed by the patient name.
> 
> Thanks to be part of this "blind" debugging session ;-) gilles

I can provide access to my HA account (if you need). Note: i'm using slightly different URL (due to my location).
In the mean time in API Response there are both patients (Sofya and Veronica).

Requested log is enclosed:
[home-assistant_librelink_2024-02-04T09-48-39.185Z - Copy.log](https://github.com/gillesvs/librelink/files/14156276/home-assistant_librelink_2024-02-04T09-48-39.185Z.-.Copy.log)
Screen of Android App:
![photo_2024-02-04_13-04-49](https://github.com/gillesvs/librelink/assets/65254375/c585994d-e4f5-4278-a75f-c46c0aa9c454)

**Comment by 1nfinity84** [comment]
Hello everyone, first of all Giles, thank you for the integration, I have so far been using a node red flow that's circulating online and helped a few people to make that work for their setup, but your integration makes this fantastically easy. 

I dropped in to share an idea the payload from llu api usually shows this: 
`{"deviceId":"","sn":"MH00U5MCFM","a":1706461617,"w":60,"pt":3,"s":true,"lj":false}` where the SN is a serial number of the sensor. So you could plot "for each sn" and then perhaps replace the SN with corresponding patient name. 

which I get in the 0 of the array returned:
{"id":"redacted","patientId":"redacted","country":"redacted","status":2,"firstName":"redacted","lastName":"redacted","targetLow":70,"targetHigh":180,"uom":0,"sensor":{"deviceId":"","sn":"MH00U5MCFM","a":1706461617,"w":60,"pt":3,"s":true,"lj":false},"alarmRules":{"c":true,"h":{"th":216,"thmm":12,"d":1440,"f":0.1},"f":{"th":55,"thmm":3,"d":30,"tl":10,"tlmm":0.6},"l":{"th":59,"thmm":3.3,"d":1440,"tl":10,"tlmm":0.6},"nd":{"i":20,"r":5,"l":6},"p":5,"r":5,"std":{}},"glucoseMeasurement":{"FactoryTimestamp":"2/4/2024 10:23:56 AM","Timestamp":"2/4/2024 11:23:56 AM","type":1,"ValueInMgPerDl":112,"TrendArrow":3,"TrendMessage":null,"MeasurementColor":1,"GlucoseUnits":0,"Value":6.2,"isHigh":false,"isLow":false},"glucoseItem":{"FactoryTimestamp":"2/4/2024 10:23:56 AM","Timestamp":"2/4/2024 11:23:56 AM","type":1,"ValueInMgPerDl":112,"TrendArrow":3,"TrendMessage":null,"MeasurementColor":1,"GlucoseUnits":0,"Value":6.2,"isHigh":false,"isLow":false},"glucoseAlarm":null,"patientDevice":{"did":"779b6d00-b300-11ee-a783-6e028cad89ed","dtid":40066,"v":"2.10.1","ll":59,"hl":216,"u":1705252473,"fixedLowAlarmValues":{"mgdl":60,"mmoll":3.3},"alarms":true,"fixedLowThreshold":0},"created":1705252595}
Or... I'm overcomplicating things, as this part of the payload returned from the api shows both patient name and the value, so you just need to combine these. 

I'd assume the payload would have multiple objects each with patientId, firstName, lastName and Value or ValueInMgPerDl...

Hope it helps :)

**Comment by KetolaSami** [comment]
I was looking at the log file, it seems to be quite clear, how it separates those two patients?
![image](https://github.com/gillesvs/librelink/assets/124524749/0e8af331-ce78-490d-b1bb-0c822d2e24ba)

**Comment by gillesvs** [comment]
> > > Dear @gillesvs! Thanks for great work! It is really useful for diabet control! In my case I cannot add second patient. Once the second patient appeared, but the first one disappeared. Now when adding I get an error:
> > > Logger: homeassistant.components.sensor Source: helpers/entity_platform.py:610 First occurred: 10:37:45 (56 occurrences) Last logged: 12:05:49
> > > Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-c1a9c786a4021b4afdddd9de55bcbe2b-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-value already exists - ignoring sensor.veronika_znamenskaia_glucose_measurement_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-trend already exists - ignoring sensor.veronika_znamenskaia_glucose_trend_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-sensor already exists - ignoring sensor.veronika_znamenskaia_active_sensor_2 Platform librelink does not generate unique IDs. ID e4a78e05-0780-11ec-ad7d-0242ac110005-f1324e683c846e1ecc2ac12e4ceb092e-delay already exists - ignoring sensor.veronika_znamenskaia_minutes_since_update_2
> > 
> > 
> > Thanks for feedback. Can you pass the integration in debug mode and send me the log? So I will finally have a look at the API response for multiple patients (as for now, I am simply guessing as Abbott does not provide official documentation of their API) Indeed, as Veronika should be a patient and not the account owner, it should not create duplicate Ids.... but there is something I do not see, that is why i need logs.
> > The **expected behavior** is, for a single account, to have as many devices created as there are patients, with sensors prefixed by the patient name.
> > Thanks to be part of this "blind" debugging session ;-) gilles
> 
> I can provide access to my HA account (if you need). Note: i'm using slightly different URL (due to my location). In the mean time in API Response there are both patients (Sofya and Veronica).
> 
> Requested log is enclosed: [home-assistant_librelink_2024-02-04T09-48-39.185Z - Copy.log](https://github.com/gillesvs/librelink/files/14156276/home-assistant_librelink_2024-02-04T09-48-39.185Z.-.Copy.log) Screen of Android App: ![photo_2024-02-04_13-04-49](https://private-user-images.githubusercontent.com/65254375/302094177-c585994d-e4f5-4278-a75f-c46c0aa9c454.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDcwNDksIm5iZiI6MTcwNzA0Njc0OSwicGF0aCI6Ii82NTI1NDM3NS8zMDIwOTQxNzctYzU4NTk5NGQtZTRmNS00Mjc4LWE3NWYtYzQ2YzBhYTljNDU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDExMzkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MmQwZTMzMzYwY2MzODRkOTYxNzBmOTYyYjIzNzdlMWIzN2RiNjY0MmM0OTA0ZjQxNWYxNjE5MjZkZTMzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-qik9O383_tOQv86soNL8de83-8YxNsW9FS6tWefgqM)

Thanks for the log!
And this is precisely what I guessed (an array of patients). So the bad news is that it confirmed what I implement in terms of logic, but does not help so much to debug.... :-)

Ideally, to do debug, I would need to test an account with two patients like yours in my test environment .
I would perfectly understand that you do not want to share your librelink account, but that would be the easiest for me to find a correction.
If ok, my email address is gilles.vanschendel@gmail.com to send me your librelink account credentials. the duration of the test phase.

**Comment by gillesvs** [comment]
> I was looking at the log file, it seems to be quite clear, how it separates those two patients? ![image](https://private-user-images.githubusercontent.com/124524749/302098390-0e8af331-ce78-490d-b1bb-0c822d2e24ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDcwNDksIm5iZiI6MTcwNzA0Njc0OSwicGF0aCI6Ii8xMjQ1MjQ3NDkvMzAyMDk4MzkwLTBlOGFmMzMxLWNlNzgtNDkwZC1iMWJiLTBjODIyZDJlMjRiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxMTM5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmEyYWQ0NzkxN2Y2OWZjNTdjM2M4MjA2ODJmY2M5ODhmYjEzMmJjZDA2ODIwNTlmY2RlZWU5YWIzOWE5NmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xAO0WsuC8y1t5eGyT9cOUizYFl5lf-pvIJvaykBEYXE)

Yes, thanks. That is what I thought and what should be working in version 1.1.5. But for some reason it does not...

**Comment by gillesvs** [comment]
Hi all,

WARNING:
@alexanderznamensky  and other sharing logs, to help me:  you might want to hide the token (I ask for the api response and the token is included). I do not need token, my objective was to understant the global API structure with multiple clients.
Because this is a long lasting token and any one with it can retreive your data.

I catch the log I needed, so feel free @alexanderznamensky  to delete the log file.

**Comment by alexanderznamensky** [comment]
my log is still existing in your reply )

**Comment by gillesvs** [comment]
> thanks! But my log is still existing in your reply )

yes, was just deleting it. It's done

**Comment by gillesvs** [comment]
Beta Release 1.1.7 tested with two patients accounts works is tested successfully.
