### ISSUE TITLE
Issue identified :  No Entities or devices found

### ISSUE THREAD

**Issue by mega-hz** [gillesvs/librelink#21]
** Which country are you from **
It helps understanding API endpoints your are using.

**Describe the bug**

**Log file**
Activate debug mode in the integration and attached the log file (if version <= 1.2.0, you might want to erase your credentials):

**Screenshots**

**Additional context**

After i setup LibreLinkup successfully and installed the Intergration i dont get any Entitys and devices!
Any Idea?

**Comment by mega-hz** [comment]
Sorry, it seems as it takes some time ...
Suddenly all sensors are there!
Everything is fine!

**Comment by liamwibo** [comment]
how long did it take for you?

**Comment by mega-hz** [comment]
I dont know the exact time, but as i installed this and the app it didnt worked for about a half an hour.
When i looked about 4 hours later there where the device and entitys available.
 
 
Von: liamwibo ***@***.***> 
Gesendet: Samstag, 29. Juni 2024 22:01
An: gillesvs/librelink ***@***.***>
Cc: mega-hz ***@***.***>; Author ***@***.***>
Betreff: Re: [gillesvs/librelink] Issue identified : No Entities or devices found (Issue #21)
 
how long did it take for you?

**Comment by WaeedHussain** [comment]
I'm having the same issue. V1.2.3 with API location set to 'global'. I've tried restarting HA and the integration but  still shows 'No Entities'.

I have seen somewhere that there may be a eu2 domain?

**Comment by Smiley1244** [comment]
Having the same issue here too, libre app is set to united kingdom. Selecting global in the add-on connects using my credentials but no entities ever appear

**Comment by WaeedHussain** [comment]
> Having the same issue here too, libre app is set to united kingdom. Selecting global in the add-on connects using my credentials but no entities ever appear

I realised my mistake. You have to setup a LibreLinkUp account and use those credentials. Essentially your libre app will send the glucose data to LibreLinkUp (used for family members) and then HA will use LibreLinkUp to feed your dashboard

**Comment by Smiley1244** [comment]
Ah ok I'll give that a go, thanks for the quick responce

**Comment by Smiley1244** [comment]
Yep that worked perfectly, thanks. A suggestion if I may? It might be worth putting that it can use mmol/l in the documentation. I nearly browsed away because I thought it only did mg/dL. It's only because I'm cheeky and was going to raise a request to have it, that I saw in the issues it already did it. 😀 Otherwise amazing add-on thanks
