### ISSUE TITLE
Issue identified : https://github.com/gillesvs/librelink is not a valid add-on repository

### ISSUE THREAD

**Issue by ArashiKorosu** [gillesvs/librelink#25]
** Which country are you from **
Portugal

**Describe the bug**
Trying to add this as a custom repo and getting "https://github.com/gillesvs/librelink is not a valid add-on repository"
I might be an idiot since I am new to HAOS sorry

**Log file**
n/a

**Screenshots**
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/6deefd8a-9252-496e-ad8b-4040b232df53">

**Additional context**
Proxmox CT with HAOS:
Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

**Comment by riegera2412** [comment]
Not sure if you got the answer already. You are trying to add the repo in Home Assistant Addons but not as an integration repository for HACS (Home Assistant Community Store). 

You have to set-up HACS first, then add the LibreLinkUp integration reposiory there. After you have downloaded it from HACS go to Home Assistant integrations, click add integration and set it up.
