### ISSUE TITLE
Feature request : 2FA support

### ISSUE THREAD

**Issue by MoshiBin** [gillesvs/librelink#28]
**Is your feature request related to a problem? Please describe.**
I tried to setup this integration but it kept failing with the following error:

```
File "/config/custom_components/librelink/config_flow.py", line 39, in async_step_user
await self._test_credentials(
File "/config/custom_components/librelink/config_flow.py", line 101, in _test_credentials
await client.async_get_token()
File "/config/custom_components/librelink/api.py", line 168, in async_get_token
monToken = reponseLogin["data"]["authTicket"]["token"]
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'authTicket'
```

I then tried to log onto the LibreView website to ensure my credentials were correct, and it made me set up two-factor authentication. Unfortunately it doesn't seem like I can remove 2FA via the website, and this integration doesn't support the 2FA flow.

**Describe the solution you'd like**
When setting up this integration, if 2FA is setup on the account, the wizard should prompt for the one-time code and set itself up as a trusted app.

**Describe alternatives you've considered**
Interestingly, I tried to follow the code and send a request manually via `requests.post`, but kept getting a `notAuthenticated` error:

```python
>>> login_url = "https://api-eu.libreview.io/llu/auth/login"
>>> data = {"email": "xxx", "password": "xxx"}
>>> headers = {"product": "llu.android", "version": "4.7", "Application": "application/json"}
>>> requests.post(login_url, data=data, headers=headers).json()
{'status': 2, 'error': {'message': 'notAuthenticated'}}
```

The only way I was able to start the 2fa negotiation is by using `https://api-eu.libreview.io/auth/login` as the endpoint:

```sh
$ curl 'https://api-eu.libreview.io/auth/login' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'newyu-lv-web-version: 3.18.15' \
  -H 'product: lv' \
  --data-raw '{"email": "xxx", "password": "xxx"}'
{"status":4,"data":{"step":{"type":"2faVerify","componentName":"TwoFactorVerify","props":{"accountType":"patient","primaryMethod":"phone","primaryValue":"+*** *********","secondaryMethod":"email","secondaryValue":"***********@gmail.com"},"title":"AccountSignUp.verifyYourIdentity"},"user":{"accountType":"pat","country":"IL","uiLanguage":"en-US"},"authTicket":{"token":"xxx","expires":1724977478,"duration":3600000}}}
```

**Comment by MoshiBin** [comment]
My bad - I kept trying to log into my LibreLink account instead of LibreLinkUp 🤦‍♂️ 
With LibreLinkUp there's no 2FA and everything works correctly.

Would you be willing to accept a PR that adds this distinction to the docs?

**Comment by gillesvs** [comment]
Hello
Sure I will

Cordialement,

Gilles van Schendel


Le ven. 30 août 2024 à 02:32, Moshi Binyamini ***@***.***> a
écrit :
