### ISSUE TITLE
Feature request : 24hrs instead of am / pm 

### ISSUE THREAD

**Issue by stresskiller** [gillesvs/librelink#29]
first of all thank you for sharing this awesome tool : 

my wife uses the mmol setting so i had to adjust your graphics a little to this : 

type: custom:mini-graph-card
entities:
  - entity: sensor.my_wife_glucose_measurement
    state_adaptive_color: true
    show_icon: true
name: Freestyle
lower_bound: 0
align_icon: left
hours_to_show: 72
points_per_hour: 15
smoothing: false
show:
  icon_adaptive_color: true
  points: hover
  state: true
  extrema: true
  average: true
color_thresholds:
  - value: 0
    color: '#ff0000'
  - value: 3
    color: '#ffa500'
  - value: 4
    color: '#fff700'
  - value: 5
    color: '#00ff00'
  - value: 10
    color: '#00ff00'
  - value: 12
    color: '#fff700'
  - value: 14
    color: '#ffa500'
  - value: 15
    color: '#ff0000'

![afbeelding](https://github.com/user-attachments/assets/0f0e0614-0fe5-43d4-ae98-8f96a16a14b7)

the only thing i can't figure out is how to get it to 24hrs instead of am / pm

**Comment by MortenVinding** [comment]
hour24: true
