### ISSUE TITLE
Unknown error at login

### ISSUE THREAD

**Issue by Stu333** [gillesvs/librelink#3]
<img width="340" alt="librelink error" src="https://github.com/gillesvs/librelink/assets/49353748/9be2ec8f-3063-492f-bb65-5fd41bd623db">
The install went Ok, however Im getting an error when trying to log in using my LibreLink credentials, see screen shot.

**Comment by gillesvs** [comment]
Hello @Stu333 ,
Are you sure of your credentials ending with ".com.au"
If so, can you send debug info?
