### ISSUE TITLE
Issue identified : Only Binarysensors high/low showing

### ISSUE THREAD

**Issue by Avpman2** [gillesvs/librelink#30]
The setup went fine, and I logged in ok. But I'm only getting two entities, binary high/low—none of the other sensor data. When I pull up LibreLink on my phone, everything is there. Log attached.

![image](https://github.com/user-attachments/assets/ab2958db-114f-490e-bbe4-aa395aa48548)

[home-assistant_librelink_2024-09-26T00-43-59.433Z.log](https://github.com/user-attachments/files/17139989/home-assistant_librelink_2024-09-26T00-43-59.433Z.log)

**Comment by gillesvs** [comment]
Hello
Did you try with LibrelinkUp credentials?
Not librelink 
Regards

**Comment by Avpman2** [comment]
Yes, I created a LibreLinkUp account and invited myself. I get a notification when I scan my sensor, so I assume it is set up and working correctly.

**Comment by Avpman2** [comment]
Why is this marked closed/completed? Do you need more info to fix?

**Comment by sinanqasha** [comment]
Same issue
