### ISSUE TITLE
mg/dL and mmol/L readings

### ISSUE THREAD

**Issue by Stu333** [gillesvs/librelink#4]
Suggestion to provide mg/dL and mmol/L readings, either as selection of unit of measure or provide two sensors (mmol/L = mg/dL divided by 18).
Freestyle LibreLink defaults unit of measure to the region/country, (e.g. Australia is mmol/L) and cant change it in the app.

**Comment by gillesvs** [comment]
Done, can you test the pre release v1.1.2b

**Comment by gillesvs** [comment]
Hi stu.
This is normal.

Go to Integrations=>librelink=>configure 

You will have to chose the unit and the sensor unit of measurement will change instantly

**Comment by gillesvs** [comment]
> Hi, appreciate your help on this. I navigated Settings>Integrations>LibreLink but I can’t see Configure; screenshot ![IMG_0528](https://private-user-images.githubusercontent.com/49353748/301759134-b7f43e85-beb1-4659-929a-ead03c16271d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjY1MjIsIm5iZiI6MTcwNjg2NjIyMiwicGF0aCI6Ii80OTM1Mzc0OC8zMDE3NTkxMzQtYjdmNDNlODUtYmViMS00NjU5LTkyOWEtZWFkMDNjMTYyNzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA5MzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NzYxYjM5MGE4YTQ1ODRjM2E2OTQ1ZWE2YjQ1OTZjZTUwMjc5NTJmYTc4MGQ0NTRjNDliMWMwZDYxNWY3YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdkSoniSTlEKv7A0Cc0HU59EV1dgI36in68IGnUFUZ0)

Hi, Strange
I have this in my test environment:

![Capture d'écran MMOL](https://github.com/gillesvs/librelink/assets/51242147/5fe6dd0b-6d5c-461f-80bb-bfc9c9150bd1)

**Comment by gillesvs** [comment]
I will try to deliver a new package

**Comment by gillesvs** [comment]
@Stu333 , new package delivered. Normally you can just update the integration without deleting everything

**Comment by gillesvs** [comment]
Thanks for your feedback. I also use this integration for custom alerts and integration with my smart watch.
